### ISSUE TITLE
datetime DEFAULT NULL leads to 

### ISSUE THREAD

**Issue by hrehfeld** [xnuinside/omymodels#51]
**To Reproduce**
testcase.sql:
```
CREATE TABLE "option" (
  "opt_date" datetime DEFAULT NULL,
);
```

`omm testcase.sql` results in:

```
Traceback (most recent call last):
  File "/home/hrehfeld/projects/ext/omymodels/.venv/bin/omm", line 8, in <module>
    sys.exit(main())
  File "/home/hrehfeld/projects/ext/omymodels/.venv/lib/python3.10/site-packages/omymodels/cli.py", line 76, in main
    result = create_models(
  File "/home/hrehfeld/projects/ext/omymodels/.venv/lib/python3.10/site-packages/omymodels/from_ddl.py", line 54, in create_models
    output = generate_models_file(
  File "/home/hrehfeld/projects/ext/omymodels/.venv/lib/python3.10/site-packages/omymodels/from_ddl.py", line 115, in generate_models_file
    models_str += generator.generate_model(
  File "/home/hrehfeld/projects/ext/omymodels/.venv/lib/python3.10/site-packages/omymodels/models/pydantic/core.py", line 103, in generate_model
    model += self.generate_attr(column, defaults_off) + "\n"
  File "/home/hrehfeld/projects/ext/omymodels/.venv/lib/python3.10/site-packages/omymodels/models/pydantic/core.py", line 67, in generate_attr
    column_str = self.add_default_values(column_str, column)
  File "/home/hrehfeld/projects/ext/omymodels/.venv/lib/python3.10/site-packages/omymodels/models/pydantic/core.py", line 78, in add_default_values
    column.default = f"'{column['default']}'"
TypeError: 'Column' object is not subscriptable
```

**Comment by xnuinside** [comment]
@hrehfeld maybe problem was in python version.. I released new version 0.14.0 - cannot reproduce issue on it. Try it and if issue will still exists - re-open it, pls. Thank you!

**Comment by rayliverified** [comment]
Hey @xnuinside, thanks for the great library! 

I ran into this issue as well. Let me document it and then see if I can help make a PR for a fix.

```sql
CREATE TABLE test_table (
  id INT NOT NULL AUTO_INCREMENT,
  create_at DATETIME DEFAULT NULL,
);
```

** Error: **
```
Traceback (most recent call last):
  File "generate_table_types.py", line 130, in <module>
    generate_pydantic_models(cleaned_schema_file, models_output_file)
  File "generate_table_types.py", line 104, in generate_pydantic_models
    result = create_models(ddl, models_type='pydantic', no_auto_snake_case=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/omymodels/from_ddl.py", line 57, in create_models
    output = generate_models_file(
             ^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/omymodels/from_ddl.py", line 149, in generate_models_file
    models_str += generator.generate_model(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/omymodels/models/pydantic/core.py", line 100, in generate_model
    model += self.generate_attr(column, defaults_off) + "\n"
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/omymodels/models/pydantic/core.py", line 64, in generate_attr
    column_str = self.add_default_values(column_str, column)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/omymodels/models/pydantic/core.py", line 75, in add_default_values
    column.default = f"'{column['default']}'"
                         ~~~~~~^^^^^^^^^^^
TypeError: 'Column' object is not subscriptable
```

The error arises because the code is attempting to access attributes of a Column object using dictionary-style indexing (e.g., column['default']), which isn't supported. Instead, attributes should be accessed using dot notation (e.g., column.default).

### Fix
1. Updated type hints to reflect that column is an instance of the Column class rather than a Dict.
```python
def add_custom_type(self, target_type: str) -> Optional[str]:
def get_not_custom_type(self, column: Column) -> str:
def generate_attr(self, column: Column, defaults_off: bool) -> str:
@staticmethod
def add_default_values(column_str: str, column: Column) -> str:
```

2. Replaced all instances of column['attribute'] with column.attribute.
```python
# Before
column.default = f"'{column['default']}'"

# After
column.default = f"'{column.default}'"
Handling DEFAULT NULL:
```

3. Added logic to set the default value to None when DEFAULT NULL is specified.
```python
if column.default.upper() == 'NULL':
    column.default = 'None'
```
